/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteCancellationRouteImport } from './routes/_site/cancellation'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteFaqRouteImport } from './routes/_site/faq'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteShareYourTripRouteImport } from './routes/_site/share-your-trip'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountBookingsRouteImport } from './routes/account/bookings'
import { Route as AccountWishlistRouteImport } from './routes/account/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminChatRouteImport } from './routes/admin/chat'
import { Route as AdminDeparturesRouteImport } from './routes/admin/departures'
import { Route as AdminFaqRouteImport } from './routes/admin/faq'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminLegalRouteImport } from './routes/admin/legal'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminPromosRouteImport } from './routes/admin/promos'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminTripsRouteImport } from './routes/admin/trips'
import { Route as AdminWaitingListRouteImport } from './routes/admin/waiting-list'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as SiteBlogIndexRouteImport } from './routes/_site/blog/index'
import { Route as SiteBlogSlugRouteImport } from './routes/_site/blog/$slug'
import { Route as SiteBlogPhotosRouteImport } from './routes/_site/blog/photos'
import { Route as SiteBlogVideosRouteImport } from './routes/_site/blog/videos'
import { Route as SiteTripsIndexRouteImport } from './routes/_site/trips/index'
import { Route as SiteTripsSlugRouteRouteImport } from './routes/_site/trips/$slug/route'
import { Route as SiteTripsCompareRouteImport } from './routes/_site/trips/compare'
import { Route as AdminTripsIdRouteImport } from './routes/admin/trips/$id'
import { Route as SiteTripsSlugIndexRouteImport } from './routes/_site/trips/$slug/index'
import { Route as SiteTripsSlugBookRouteRouteImport } from './routes/_site/trips/$slug/book/route'
import { Route as SiteTripsSlugBookIndexRouteImport } from './routes/_site/trips/$slug/book/index'
import { Route as SiteTripsSlugBookConfirmRouteImport } from './routes/_site/trips/$slug/book/confirm'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCancellationRoute = SiteCancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShareYourTripRoute = SiteShareYourTripRouteImport.update({
  id: '/share-your-trip',
  path: '/share-your-trip',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeparturesRoute = AdminDeparturesRouteImport.update({
  id: '/departures',
  path: '/departures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWaitingListRoute = AdminWaitingListRouteImport.update({
  id: '/waiting-list',
  path: '/waiting-list',
  getParentRoute: () => AdminRoute,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogPhotosRoute = SiteBlogPhotosRouteImport.update({
  id: '/blog/photos',
  path: '/blog/photos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogVideosRoute = SiteBlogVideosRouteImport.update({
  id: '/blog/videos',
  path: '/blog/videos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTripsIndexRoute = SiteTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTripsSlugRouteRoute = SiteTripsSlugRouteRouteImport.update({
  id: '/trips/$slug',
  path: '/trips/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTripsCompareRoute = SiteTripsCompareRouteImport.update({
  id: '/trips/compare',
  path: '/trips/compare',
  getParentRoute: () => SiteRoute,
} as any)
const AdminTripsIdRoute = AdminTripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTripsRoute,
} as any)
const SiteTripsSlugIndexRoute = SiteTripsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteTripsSlugRouteRoute,
} as any)
const SiteTripsSlugBookRouteRoute = SiteTripsSlugBookRouteRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => SiteTripsSlugRouteRoute,
} as any)
const SiteTripsSlugBookIndexRoute = SiteTripsSlugBookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteTripsSlugBookRouteRoute,
} as any)
const SiteTripsSlugBookConfirmRoute =
  SiteTripsSlugBookConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => SiteTripsSlugBookRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof SiteAboutRoute
  '/cancellation': typeof SiteCancellationRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/privacy': typeof SitePrivacyRoute
  '/share-your-trip': typeof SiteShareYourTripRoute
  '/terms': typeof SiteTermsRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/departures': typeof AdminDeparturesRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/trips': typeof AdminTripsRouteWithChildren
  '/admin/waiting-list': typeof AdminWaitingListRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/trips/$slug': typeof SiteTripsSlugRouteRouteWithChildren
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/blog/photos': typeof SiteBlogPhotosRoute
  '/blog/videos': typeof SiteBlogVideosRoute
  '/trips/compare': typeof SiteTripsCompareRoute
  '/admin/trips/$id': typeof AdminTripsIdRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/trips/': typeof SiteTripsIndexRoute
  '/trips/$slug/book': typeof SiteTripsSlugBookRouteRouteWithChildren
  '/trips/$slug/': typeof SiteTripsSlugIndexRoute
  '/trips/$slug/book/confirm': typeof SiteTripsSlugBookConfirmRoute
  '/trips/$slug/book/': typeof SiteTripsSlugBookIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof SiteAboutRoute
  '/cancellation': typeof SiteCancellationRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/privacy': typeof SitePrivacyRoute
  '/share-your-trip': typeof SiteShareYourTripRoute
  '/terms': typeof SiteTermsRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/departures': typeof AdminDeparturesRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/trips': typeof AdminTripsRouteWithChildren
  '/admin/waiting-list': typeof AdminWaitingListRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/': typeof SiteIndexRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/blog/photos': typeof SiteBlogPhotosRoute
  '/blog/videos': typeof SiteBlogVideosRoute
  '/trips/compare': typeof SiteTripsCompareRoute
  '/admin/trips/$id': typeof AdminTripsIdRoute
  '/blog': typeof SiteBlogIndexRoute
  '/trips': typeof SiteTripsIndexRoute
  '/trips/$slug': typeof SiteTripsSlugIndexRoute
  '/trips/$slug/book/confirm': typeof SiteTripsSlugBookConfirmRoute
  '/trips/$slug/book': typeof SiteTripsSlugBookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/cancellation': typeof SiteCancellationRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/share-your-trip': typeof SiteShareYourTripRoute
  '/_site/terms': typeof SiteTermsRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/departures': typeof AdminDeparturesRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/trips': typeof AdminTripsRouteWithChildren
  '/admin/waiting-list': typeof AdminWaitingListRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/_site/': typeof SiteIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/trips/$slug': typeof SiteTripsSlugRouteRouteWithChildren
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/blog/photos': typeof SiteBlogPhotosRoute
  '/_site/blog/videos': typeof SiteBlogVideosRoute
  '/_site/trips/compare': typeof SiteTripsCompareRoute
  '/admin/trips/$id': typeof AdminTripsIdRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/_site/trips/': typeof SiteTripsIndexRoute
  '/_site/trips/$slug/book': typeof SiteTripsSlugBookRouteRouteWithChildren
  '/_site/trips/$slug/': typeof SiteTripsSlugIndexRoute
  '/_site/trips/$slug/book/confirm': typeof SiteTripsSlugBookConfirmRoute
  '/_site/trips/$slug/book/': typeof SiteTripsSlugBookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/about'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/share-your-trip'
    | '/terms'
    | '/account/bookings'
    | '/account/wishlist'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/departures'
    | '/admin/faq'
    | '/admin/homepage'
    | '/admin/legal'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/promos'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/trips'
    | '/admin/waiting-list'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/account/'
    | '/admin/'
    | '/trips/$slug'
    | '/blog/$slug'
    | '/blog/photos'
    | '/blog/videos'
    | '/trips/compare'
    | '/admin/trips/$id'
    | '/blog/'
    | '/trips/'
    | '/trips/$slug/book'
    | '/trips/$slug/'
    | '/trips/$slug/book/confirm'
    | '/trips/$slug/book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/about'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/share-your-trip'
    | '/terms'
    | '/account/bookings'
    | '/account/wishlist'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/departures'
    | '/admin/faq'
    | '/admin/homepage'
    | '/admin/legal'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/promos'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/trips'
    | '/admin/waiting-list'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/'
    | '/account'
    | '/admin'
    | '/blog/$slug'
    | '/blog/photos'
    | '/blog/videos'
    | '/trips/compare'
    | '/admin/trips/$id'
    | '/blog'
    | '/trips'
    | '/trips/$slug'
    | '/trips/$slug/book/confirm'
    | '/trips/$slug/book'
  id:
    | '__root__'
    | '/_site'
    | '/account'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_site/about'
    | '/_site/cancellation'
    | '/_site/contact'
    | '/_site/faq'
    | '/_site/privacy'
    | '/_site/share-your-trip'
    | '/_site/terms'
    | '/account/bookings'
    | '/account/wishlist'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/departures'
    | '/admin/faq'
    | '/admin/homepage'
    | '/admin/legal'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/promos'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/trips'
    | '/admin/waiting-list'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/_site/'
    | '/account/'
    | '/admin/'
    | '/_site/trips/$slug'
    | '/_site/blog/$slug'
    | '/_site/blog/photos'
    | '/_site/blog/videos'
    | '/_site/trips/compare'
    | '/admin/trips/$id'
    | '/_site/blog/'
    | '/_site/trips/'
    | '/_site/trips/$slug/book'
    | '/_site/trips/$slug/'
    | '/_site/trips/$slug/book/confirm'
    | '/_site/trips/$slug/book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cancellation': {
      id: '/_site/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof SiteCancellationRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/share-your-trip': {
      id: '/_site/share-your-trip'
      path: '/share-your-trip'
      fullPath: '/share-your-trip'
      preLoaderRoute: typeof SiteShareYourTripRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/bookings': {
      id: '/account/bookings'
      path: '/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departures': {
      id: '/admin/departures'
      path: '/departures'
      fullPath: '/admin/departures'
      preLoaderRoute: typeof AdminDeparturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/waiting-list': {
      id: '/admin/waiting-list'
      path: '/waiting-list'
      fullPath: '/admin/waiting-list'
      preLoaderRoute: typeof AdminWaitingListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/photos': {
      id: '/_site/blog/photos'
      path: '/blog/photos'
      fullPath: '/blog/photos'
      preLoaderRoute: typeof SiteBlogPhotosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/videos': {
      id: '/_site/blog/videos'
      path: '/blog/videos'
      fullPath: '/blog/videos'
      preLoaderRoute: typeof SiteBlogVideosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/trips/': {
      id: '/_site/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof SiteTripsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/trips/$slug': {
      id: '/_site/trips/$slug'
      path: '/trips/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof SiteTripsSlugRouteRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/trips/compare': {
      id: '/_site/trips/compare'
      path: '/trips/compare'
      fullPath: '/trips/compare'
      preLoaderRoute: typeof SiteTripsCompareRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/trips/$id': {
      id: '/admin/trips/$id'
      path: '/$id'
      fullPath: '/admin/trips/$id'
      preLoaderRoute: typeof AdminTripsIdRouteImport
      parentRoute: typeof AdminTripsRoute
    }
    '/_site/trips/$slug/': {
      id: '/_site/trips/$slug/'
      path: '/'
      fullPath: '/trips/$slug/'
      preLoaderRoute: typeof SiteTripsSlugIndexRouteImport
      parentRoute: typeof SiteTripsSlugRouteRoute
    }
    '/_site/trips/$slug/book': {
      id: '/_site/trips/$slug/book'
      path: '/book'
      fullPath: '/trips/$slug/book'
      preLoaderRoute: typeof SiteTripsSlugBookRouteRouteImport
      parentRoute: typeof SiteTripsSlugRouteRoute
    }
    '/_site/trips/$slug/book/': {
      id: '/_site/trips/$slug/book/'
      path: '/'
      fullPath: '/trips/$slug/book/'
      preLoaderRoute: typeof SiteTripsSlugBookIndexRouteImport
      parentRoute: typeof SiteTripsSlugBookRouteRoute
    }
    '/_site/trips/$slug/book/confirm': {
      id: '/_site/trips/$slug/book/confirm'
      path: '/confirm'
      fullPath: '/trips/$slug/book/confirm'
      preLoaderRoute: typeof SiteTripsSlugBookConfirmRouteImport
      parentRoute: typeof SiteTripsSlugBookRouteRoute
    }
  }
}

interface SiteTripsSlugBookRouteRouteChildren {
  SiteTripsSlugBookConfirmRoute: typeof SiteTripsSlugBookConfirmRoute
  SiteTripsSlugBookIndexRoute: typeof SiteTripsSlugBookIndexRoute
}

const SiteTripsSlugBookRouteRouteChildren: SiteTripsSlugBookRouteRouteChildren =
  {
    SiteTripsSlugBookConfirmRoute: SiteTripsSlugBookConfirmRoute,
    SiteTripsSlugBookIndexRoute: SiteTripsSlugBookIndexRoute,
  }

const SiteTripsSlugBookRouteRouteWithChildren =
  SiteTripsSlugBookRouteRoute._addFileChildren(
    SiteTripsSlugBookRouteRouteChildren,
  )

interface SiteTripsSlugRouteRouteChildren {
  SiteTripsSlugBookRouteRoute: typeof SiteTripsSlugBookRouteRouteWithChildren
  SiteTripsSlugIndexRoute: typeof SiteTripsSlugIndexRoute
}

const SiteTripsSlugRouteRouteChildren: SiteTripsSlugRouteRouteChildren = {
  SiteTripsSlugBookRouteRoute: SiteTripsSlugBookRouteRouteWithChildren,
  SiteTripsSlugIndexRoute: SiteTripsSlugIndexRoute,
}

const SiteTripsSlugRouteRouteWithChildren =
  SiteTripsSlugRouteRoute._addFileChildren(SiteTripsSlugRouteRouteChildren)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteCancellationRoute: typeof SiteCancellationRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteShareYourTripRoute: typeof SiteShareYourTripRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteTripsSlugRouteRoute: typeof SiteTripsSlugRouteRouteWithChildren
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteBlogPhotosRoute: typeof SiteBlogPhotosRoute
  SiteBlogVideosRoute: typeof SiteBlogVideosRoute
  SiteTripsCompareRoute: typeof SiteTripsCompareRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
  SiteTripsIndexRoute: typeof SiteTripsIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteCancellationRoute: SiteCancellationRoute,
  SiteContactRoute: SiteContactRoute,
  SiteFaqRoute: SiteFaqRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteShareYourTripRoute: SiteShareYourTripRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteTripsSlugRouteRoute: SiteTripsSlugRouteRouteWithChildren,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteBlogPhotosRoute: SiteBlogPhotosRoute,
  SiteBlogVideosRoute: SiteBlogVideosRoute,
  SiteTripsCompareRoute: SiteTripsCompareRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
  SiteTripsIndexRoute: SiteTripsIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AccountRouteChildren {
  AccountBookingsRoute: typeof AccountBookingsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountBookingsRoute: AccountBookingsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminTripsRouteChildren {
  AdminTripsIdRoute: typeof AdminTripsIdRoute
}

const AdminTripsRouteChildren: AdminTripsRouteChildren = {
  AdminTripsIdRoute: AdminTripsIdRoute,
}

const AdminTripsRouteWithChildren = AdminTripsRoute._addFileChildren(
  AdminTripsRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminDeparturesRoute: typeof AdminDeparturesRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminTripsRoute: typeof AdminTripsRouteWithChildren
  AdminWaitingListRoute: typeof AdminWaitingListRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminChatRoute: AdminChatRoute,
  AdminDeparturesRoute: AdminDeparturesRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminTripsRoute: AdminTripsRouteWithChildren,
  AdminWaitingListRoute: AdminWaitingListRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
